'use client'

import { useRef } from 'react'
import { Button } from '@/components/ui/button'
import { toPng } from 'html-to-image'

interface UserData {
  login: string;
  name?: string;
  followers: number;
  following: number;
  public_repos: number;
}

interface Repo {
  id: number;
  name: string;
  stargazers_count: number;
}

interface ReceiptProps {
  userData: UserData;
  topRepos: Repo[];
}

export function Receipt({ userData, topRepos }: ReceiptProps) {
  const receiptRef = useRef(null)

  const downloadReceipt = async () => {
    if (receiptRef.current) {
      const dataUrl = await toPng(receiptRef.current, {
        fontEmbedCSS: '@import url("https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap");'
      })
      const link = document.createElement('a')
      link.download = `${userData.login}-github-receipt.png`
      link.href = dataUrl
      link.click()
    }
  }

  return (
    <div className="flex flex-col items-center">
      <div 
        ref={receiptRef} 
        className="bg-white dark:bg-gray-800 p-6 w-72 font-mono text-xs leading-tight shadow-lg rounded-lg"
        style={{ fontFamily: '"Roboto Mono", monospace' }}
      >
        <div className="text-center mb-4 border-b border-dashed pb-2">
          <h2 className="text-lg font-bold">GitHub Receipt</h2>
          <p className="text-xs">{new Date().toLocaleDateString()}</p>
        </div>
        <div className="mb-4">
          <p className="font-bold">{userData.name || userData.login}</p>
          <p>@{userData.login}</p>
        </div>
        <table className="w-full mb-4">
          <tbody>
            <tr>
              <td>Followers</td>
              <td className="text-right">{userData.followers}</td>
            </tr>
            <tr>
              <td>Following</td>
              <td className="text-right">{userData.following}</td>
            </tr>
            <tr>
              <td>Public Repos</td>
              <td className="text-right">{userData.public_repos}</td>
            </tr>
          </tbody>
        </table>
        <div className="border-t border-b border-dashed py-2 mb-4">
          <p className="font-bold mb-1">Top Repositories:</p>
          {topRepos.map((repo, index) => (
            <p key={repo.id} className="text-xs truncate">
              {index + 1}. {repo.name} - ⭐ {repo.stargazers_count}
            </p>
          ))}
        </div>
        <div className="text-center text-xs mt-4 border-t border-dashed pt-2">
          <p>Generated by GitHub Receipt</p>
        </div>
      </div>
      <Button onClick={downloadReceipt} className="mt-4 w-full">Download Receipt</Button>
    </div>
  )
}

